### PR TITLE
Updating for latest spotify shas  and installer

### PR DESCRIPTION
**Pull request by irabinovitch**
Update Spotify checksum and run installer, rather than copying installer to /Application.

### CODE REVIEW

**Comment by irabinovitch** [comment]
@juliandunn any objections to rewriting this to use the ARK resource instead of execute blocks?

**Comment by juliandunn** [comment]
I'm not that familiar with the ark resource, but seems fine to me.

However my use case is slightly different than what you've got here which is that you are opening the installer immediately assuming an interactive session. I only run Chef on my Mac in non-interactive mode.

**Comment by irabinovitch** [comment]
That was my goal as well, but there doesn't seem to be a way to do an unattended install of Spotify, so my goal of an end to end setup of a new laptop trumped my desire for it being entirely non-interactive.  

Anyways, I can remove the install blocks and have it just unzip/expand the installer. In either case the old urls and hashes no longer worked.

**Comment by juliandunn** [comment]
Yeah. I guess I am willing to live with just automating as much as possible since I have other apps (e.g. Sophos Anti-Virus) that can't fully be installed without someone being present to run an interactive installer.

So if there only are checksum fixes to be made here, can you rebase and make those?

**Pull request closed without merging**
